apiVersion: v1
kind: Service
metadata:
  name: dashy-lb
  namespace: ingress
  # namespace: dashy
  annotations:
    metallb.universe.tf/allow-shared-ip: "dashy-shared-ip"
spec:
  selector:
    # app: dashy
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.13
  ports:
    - name: dashy
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
  namespace: dashy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: dashy.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashy
                port:
                  number: 4000
