---
- name: nfs | Apply the NFS service settings
  truenas_config:
    namespace: nfs
    settings: "{{ truenas_nfs_settings }}"
  when: truenas_nfs_settings | length > 0

- name: nfs | Create or update the NFS shares
  truenas_resource:
    namespace: sharing.nfs
    key: [path]
    entries: "{{ truenas_nfs_shares }}"
    defaults: "{{ truenas_nfs_share_defaults }}"
  when: truenas_nfs_shares | length > 0
