"""requirements.txt matches requirements.in: every direct pin is locked at that version, and every package is hashed.

requirements.txt is generated by `make lock`, never edited by hand, and CI installs it alone. Without this test a
pin changed in requirements.in without a relock, or a lock edited by hand, would pass CI unnoticed.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def canonical(name):
    """The package name as PEP 503 normalises it, so ruamel.yaml.clib and ruamel-yaml-clib are one package."""
    return re.sub(r"[-_.]+", "-", name).lower()


def direct_pins():
    """{name: version} from requirements.in."""
    pins = {}
    for line in (ROOT / "requirements.in").read_text().splitlines():
        requirement = line.split("#", 1)[0].strip()
        if requirement:
            name, pinned, version = requirement.partition("==")
            assert pinned, f"requirements.in: {requirement!r} is not pinned with =="
            pins[canonical(name)] = version.strip()
    return pins


def locked():
    """{name: (version, number of hashes)} from requirements.txt."""
    packages, current = {}, None
    for line in (ROOT / "requirements.txt").read_text().splitlines():
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        if not line[0].isspace():
            name, _, version = text.rstrip("\\").split(";", 1)[0].partition("==")
            current = canonical(name.strip())
            packages[current] = (version.strip(), 0)
        elif text.startswith("--hash=") and current:
            version, hashes = packages[current]
            packages[current] = (version, hashes + 1)
    return packages


def test_every_direct_pin_is_locked_at_its_version():
    lock = locked()
    problems = [
        f"{name}: requirements.in pins {version}, requirements.txt has {lock[name][0] if name in lock else 'nothing'}"
        for name, version in direct_pins().items()
        if lock.get(name, (None,))[0] != version
    ]
    assert not problems, "\n".join(problems) + "\nRun `make lock`."


def test_every_locked_package_is_hashed():
    unhashed = [f"{name}=={version}" for name, (version, hashes) in locked().items() if not hashes]
    assert not unhashed, f"requirements.txt has no --hash for {', '.join(unhashed)}. Run `make lock`."
