"""poetry.lock matches pyproject.toml: every pin is exact and locked at its version, and every package is hashed.

poetry.lock is generated by `make lock`, never edited by hand, and CI installs it alone. `poetry check --lock` (make
lint-lock) proves the lock was made from pyproject.toml, but not that the locked versions are the pinned ones or that
each package has hashes: Poetry installs a package the lock records no file hashes for without checking anything.
"""

import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[2]


def pyproject():
    return tomllib.loads((ROOT / "pyproject.toml").read_text())


def lock():
    return tomllib.loads((ROOT / "poetry.lock").read_text())


def direct_pins():
    """{name: version} from [project] dependencies and every PEP 735 dependency group."""
    project = pyproject()
    requirements = list(project["project"]["dependencies"])
    for group in project.get("dependency-groups", {}).values():
        requirements += [r for r in group if isinstance(r, str)]
    pins = {}
    for text in requirements:
        requirement = Requirement(text)
        specifiers = list(requirement.specifier)
        assert len(specifiers) == 1 and specifiers[0].operator == "==", (
            f"pyproject.toml: {text!r} is not pinned with =="
        )
        pins[canonicalize_name(requirement.name)] = specifiers[0].version
    return pins


def test_dependencies_are_declared_only_where_the_pins_are_read():
    poetry = pyproject()["tool"]["poetry"]
    assert "dependencies" not in poetry, "declare dependencies in [project], not [tool.poetry.dependencies]"
    for name, group in poetry.get("group", {}).items():
        assert "dependencies" not in group, f"declare the {name} group in [dependency-groups], not [tool.poetry.group]"


def test_every_direct_pin_is_locked_at_its_version():
    locked = {package["name"]: package["version"] for package in lock()["package"]}
    problems = [
        f"{name}: pyproject.toml pins {version}, poetry.lock has {locked.get(name, 'nothing')}"
        for name, version in direct_pins().items()
        if locked.get(name) != version
    ]
    assert not problems, "\n".join(problems) + "\nRun `make lock`."


def test_every_locked_package_is_hashed():
    unhashed = [
        f"{package['name']}=={package['version']}"
        for package in lock()["package"]
        if not package.get("files") or not all(f.get("hash", "").startswith("sha256:") for f in package["files"])
    ]
    assert not unhashed, f"poetry.lock has no sha256 hash for every file of {', '.join(unhashed)}. Run `make lock`."


def test_lock_keeps_the_cooldown_and_installs_wheels_only():
    settings = tomllib.loads((ROOT / "poetry.toml").read_text())
    assert settings["solver"]["min-release-age"] >= 7
    assert settings["installer"]["only-binary"] == ":all:"
