---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr
          imagePullPolicy: Always
          ports:
            - containerPort: 8989
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - mountPath: /config
              name: sonarr
            - mountPath: /data
              name: sonarr-data
      volumes:
        - name: sonarr
          hostPath:
            path: /opt/sonarr/config
        - name: sonarr-data
          hostPath:
            path: /opt/media/data
