---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-lb
  namespace: ingress
  # namespace: sabnzbd
  annotations:
    metallb.universe.tf/allow-shared-ip: "sabnzbd-shared-ip"
spec:
  selector:
    # app: sabnzbd
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.21
  ports:
    - name: sabnzbd
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-ingress
  namespace: sabnzbd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: sabnzbd.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080
