---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashdot
  namespace: monitoring
  labels:
    app: dashdot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashdot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dashdot
    spec:
      containers:
        - image: mauricenino/dashdot:latest
          imagePullPolicy: Always
          name: dash
          ports:
            - containerPort: 3001
          env:
            - name: DASHDOT_PORT
              value: "3001"
            - name: DASHDOT_SHOW_HOST
              value: "true"
            - name: DASHDOT_SHOW_DASH_VERSION
              value: "bottom_right"
            - name: DASHDOT_ENABLE_CPU_TEMPS
              value: "true"
            - name: DASHDOT_USE_IMPERIAL
              value: "true"
            - name: DASHDOT_ALWAYS_SHOW_PERCENTAGES
              value: "true"
            - name: DASHDOT_WIDGET_LIST
              value: "os,cpu,storage,ram,network"
            - name: DASHDOT_ACCEPT_OOKLA_EULA
              value: "true"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /mnt/host
              name: dash-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: dash-claim0
          persistentVolumeClaim:
            claimName: dash-claim0
            readOnly: true
