apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-sa-clusteradmin
  namespace: portainer
  labels:
    app: portainer
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
