---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cadvisor-ingress
  namespace: monitoring
spec:
  rules:
    - host: cadvisor.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cadvisor
                port:
                  number: 8080
