---
apiVersion: v1
kind: Secret
metadata:
  name: photoprism-secrets
  namespace: photoprism
type: Opaque
data:
  PHOTOPRISM_DATABASE_USER: x
  PHOTOPRISM_DATABASE_NAME: x
  PHOTOPRISM_DATABASE_PASSWORD: x
  PHOTOPRISM_ADMIN_PASSWORD: <your admin password here>
  PHOTOPRISM_DATABASE_DSN: username:password@tcp(db-server-address:3306)/dbname?charset=utf8mb4,utf8&parseTime=true
