---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-opt-volume
  namespace: photoprism
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #hostPath:
  #  path: "/opt/nextcloud/db"
  nfs:
    path: /mnt/nvme/store/photoprism/db
    server: truenas.local
    readOnly: false
