---

- name: snapd install classic microk8s
  snap:
    name: microk8s
    state: present
    classic: true
    channel: 1.27/stable

- name: wait for microk8s to start
  command: microk8s.status --wait-ready
  changed_when: false
  register: microk8sstatus
  failed_when:
      - "'This MicroK8s deployment is acting as a node in a cluster.' not in microk8sstatus.stdout_lines"
      - microk8sstatus.rc > 0

- name: Add user to Docker and Microk8s groups, they will need to logout and in again
  user:
    name: "{{ username }}"
    state: present
    groups:
      - docker
      - microk8s
    append: true

- name: enable microk8s services
  command: "microk8s enable {{ item }}"
  with_items: 
    - dashboard
    - dns
    - registry
    - storage
    - ingress

- name: add alias kubectl=microk8s kubectl
  lineinfile:
    path: "$HOME/.bashrc"
    regexp: "^alias kubectl="
    line: 'alias kubectl="microk8s kubectl"'
    state: present

- name: add bash completion for kubectl
  lineinfile:
    path: "$HOME/.bashrc"
    regexp: '^source <\(kubectl completion bash'
    line: "source <(kubectl completion bash)"
    state: present
  