---
- name: Install classic microk8s with snapd
  community.general.snap:
    name: microk8s
    state: present
    classic: true
    channel: 1.26/stable

- name: Wait for microk8s to start
  ansible.builtin.command: microk8s.status --wait-ready
  changed_when: false
  register: microk8sstatus
  failed_when:
    - "'This MicroK8s deployment is acting as a node in a cluster.' not in microk8sstatus.stdout_lines"
    - microk8sstatus.rc > 0

- name: Add user to docker and microk8s groups
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    groups:
      - docker
      - microk8s
    append: true

- name: enable microk8s services
  command: "microk8s enable {{ item }}"
  with_items:
    - dashboard
    - dns
    - registry
    - storage
    - ingress
