---

- name: Install microk8s
  ansible.builtin.include_tasks: "install_microk8s.yml"

- name: Setup k8s
  ansible.builtin.include_tasks: "setup.yml"

- name: Provision containers
  ansible.builtin.include_tasks: "provision.yml"