---

# Home assistant

- name: create home assistant namespace
  ansible.builtin.command: >
    kubectl create namespace homeassistant

- name: Start kubernetes homeassistant service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homeassistant

# Monitoring

- name: create monitoring namespace
  ansible.builtin.command: >
    kubectl create namespace monitoring

# Prometheus
- name: Start kubernetes prometheus service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/prometheus

# Grafana
- name: Start kubernetes grafana service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/grafana

# Homepage

- name: create homepage namespace
  ansible.builtin.command: >
    kubectl create namespace homepage

- name: Start kubernetes homepage service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homepage

# Wait for pods
# - name: Wait for pods to be ready
#   ansible.builtin.command: >
#     kubectl wait pod --all --for=condition=Ready