---

# Home assistant

- name: Start kubernetes homeassistant service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homeassistant

# Prometheus
- name: Start kubernetes prometheus service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/prometheus

# Grafana
- name: Start kubernetes grafana service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/grafana

# Homepage

- name: create homepage namespace
  register: ignore
  # ignore failed on exists error
  failed_when: ignore.rc == 2
  ansible.builtin.command: >
    kubectl create namespace homepage

- name: Start kubernetes homepage service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homepage

# Jellyfin

- name: create jellyfin namespace
  register: ignore
  # ignore failed on exists error
  failed_when: ignore.rc == 2
  ansible.builtin.command: >
    kubectl create namespace jellyfin

- name: Start kubernetes jellyfin service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/jellyfin


# Sonarr

- name: create sonarr namespace
  register: ignore
  # ignore failed on exists error
  failed_when: ignore.rc == 2
  ansible.builtin.command: >
    kubectl create namespace sonarr

- name: Start kubernetes sonarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/sonarr


# Wait for pods
# - name: Wait for pods to be ready
#   ansible.builtin.command: >
#     kubectl wait pod --all --for=condition=Ready
