---

# Home assistant

- name: Start kubernetes homeassistant service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homeassistant

# Prometheus
- name: Start kubernetes prometheus service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/prometheus

# Grafana
- name: Start kubernetes grafana service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/grafana

# Homepage

- name: Start kubernetes homepage service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homepage

# Jellyfin

- name: Start kubernetes jellyfin service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/jellyfin

# Sonarr

- name: Start kubernetes sonarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/sonarr

# Radarr

- name: Start kubernetes radarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/radarr


# Wait for pods
# - name: Wait for pods to be ready
#   ansible.builtin.command: >
#     kubectl wait pod --all --for=condition=Ready
