# Home assistant
- name: Start kubernetes homeassistant service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homeassistant

# ------ Monitoring ------

# Prometheus
- name: Start kubernetes prometheus service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/prometheus

# Grafana
- name: Start kubernetes grafana service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/grafana

# Node Exporter
- name: Start kubernetes node-exporter service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/node-exporter

# Cadvisor
- name: Start kubernetes cadvisor service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/cadvisor

# ------ End monitoring ------

# Homepage
- name: Start kubernetes homepage service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/homepage

# Jellyfin
- name: Start kubernetes jellyfin service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/jellyfin

# Sonarr
- name: Start kubernetes sonarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/sonarr

# Radarr
- name: Start kubernetes radarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/radarr

# Prowlarr
- name: Start kubernetes prowlarr service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/prowlarr

# Nextcloud
- name: Start kubernetes nextcloud service
  ansible.builtin.command: >
    kubectl apply -f /homeserver/k8s/nextcloud


# Wait for pods
# - name: Wait for pods to be ready
#   ansible.builtin.command: >
#     kubectl wait pod --all --for=condition=Ready
