---

- name: Start kubernetes ingress controller
  ansible.builtin.command: >
    microk8s kubectl apply -f /homeserver/k8s/ingress

- name: Start kubernetes homeassistant service
  ansible.builtin.command: >
    microk8s kubectl apply -f /homeserver/k8s/homeassistant

- name: Start kubernetes homepage service
  ansible.builtin.command: >
    microk8s kubectl apply -f /homeserver/k8s/homepage

- name: Start kubernetes prometheus service
  ansible.builtin.command: >
    microk8s kubectl apply -f /homeserver/k8s/prometheus