---
- name: Create .kube folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Create kubectl config
  ansible.builtin.command: microk8s config > /home/{{ username }}/.kube/config
  # changed_when: "[ -f /home/{{ username }}/.kube/config ] && echo 1 || echo 0"

- name: Create alias microk8s.kubectl=kubectl
  ansible.builtin.command: "snap alias microk8s.kubectl kubectl"
  register: "k8s_kastdout"
  changed_when: "k8s_kastdout.stdout is none"

- name: Add bash completion for kubectl
  ansible.builtin.lineinfile:
    path: "$HOME/.bashrc"
    regexp: '^source <\(kubectl completion bash'
    line: "source <(kubectl completion bash)"
    state: present

# TODO: The following corresponds with "local_addresses" in inventory file
# ex:
# [local_addresses]
# 192.168.41.221 name=homeserver1
# 192.168.41.222 name=homeserver2
#
# - name: update the /etc/hosts file with internal addresses
#   tags: etchostsupdate
#   lineinfile:
#     dest: "/etc/hosts"
#     regexp: ".*\t{{ hostvars[item]['name']}}\t{{ hostvars[item]['name']}}"
#     line: "{{ item }}\t{{ hostvars[item]['name']}}"
#     state: present
#     backup: yes
#   register: etchostsupdate
#   when: inventory_hostname != "{{ item }}" or inventory_hostname == "{{ item }}"
#   with_items: "{{groups['local_addresses']}}"

- name: Allow privileged for kubelet
  ansible.builtin.lineinfile:
    dest: /var/snap/microk8s/current/args/kubelet
    line: "--allow-privileged=true"
    state: present

- name: Allow privileged for kube-apiserver
  ansible.builtin.lineinfile:
    dest: /var/snap/microk8s/current/args/kube-apiserver
    line: "--allow-privileged=true"
    state: present
