apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: jellyfin
  annotations:
    kubernetes.io/ingress.class: "nginx" 
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
#    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
#    nginx.ingress.kubernetes.io/app-root:  
spec:
  rules:
  - host: jellyfin.homeserver.internal
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: jellyfin-tcp
            port: 
              number: 8096 
#  tls:
#  - hosts:
#    - jellyfin.mydomain.com
#    secretName: jellyfin.mydomain.com-tls # < cert-manager will store the created certificate in this secret.