---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-config
  namespace: jellyfin
spec:
  storageClassName: nfs
  volumeName: jellyfin-opt-volume
  accessModes:
    - ReadWriteMany
  #  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc-data
  namespace: jellyfin
spec:
  storageClassName: nfs
  volumeName: jellyfin-opt-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2T
