---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-opt-volume
  namespace: jellyfin
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ephemeral/jellyfin/jellyfin/config
    server: 10.0.0.64
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-opt-data
  namespace: jellyfin
spec:
  storageClassName: nfs
  capacity:
    storage: 2T
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ephemeral/jellyfin/jellyfin/data
    server: 10.0.0.64
    readOnly: false
