apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  selector:
    app: jellyfin
  # Using NodePort to access with IP Address
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 30006