---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  secretName: homepage-cert-tls
  issuerRef:
    name: lets-encrypt-staging
    kind: ClusterIssuer
  commonName: homeserver.homes
  dnsNames:
    - homeserver.homes

#  acme:
#    config:
#    - dns01:
#        provider: acmedns
#      domains:
#        - homeserver.internal
#        - "*.homeserver.internal"
