apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-app
  namespace: default
spec:
  dnsNames:
    # TODO: replace with vars
    - kawaho.me
    - www.kawaho.me
  secretName: homeserver-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
