---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  secretName: homepage-cert-tls
  issuerRef:
    name: lets-encrypt-staging
  commonName: homeserver.internal
  dnsNames:
  - homeserver.internal

#  acme:
#    config:
#    - dns01:
#        provider: acmedns
#      domains:
#        - homeserver.internal
#        - "*.homeserver.internal"