---
- name: Converge
  hosts: all

  tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Ubuntu'

    - name: "Include main"
      include_role:
        name: "main"
