# setup.yml
packages:
  - vim
  - htop
  - curl
  - tmux
  - neofetch
  - speedtest-cli
  - git-all
  - snapd
  - python3-pip
  - net-tools
  - wireshark
  - nmap
  # Minikube <1.23
  - conntrack
# ssh.yml
ssh_port: 22
# debian
# ubuntu-ufw.yml
ufw_rules:
  - rule: allow
    interface: "{{ ansible_default_ipv4['interface'] }}"
    to_port: 22
    protocol: tcp
