apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA==
  MYSQL_USER: bmV4dGNsb3Vk
  MYSQL_PASSWORD: cGFzc3dvcmQ=
