apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud        
  namespace: nextcloud   
  labels:                         
    app: nextcloud       
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 0                 
      maxUnavailable: 1           
    type: RollingUpdate           
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: ghcr.io/linuxserver/nextcloud 
        name: nextcloud                   
        imagePullPolicy: Always          
        env:                             
        - name: PGID
          value: "100" 
        - name: PUID
          value: "1041"
        - name: TZ
          value: Europe/Amsterdam
        ports:
         - containerPort: 443       
           name: https
           protocol: TCP
         - containerPort: 80       
           name: http
           protocol: TCP
        volumeMounts:               
         - mountPath: /config              
           name: nextcloud
           subPath: config
         - mountPath: /data
           name: nextcloud
           subPath: data 
      volumes:
      - name: nextcloud        
        persistentVolumeClaim:
          claimName: nextcloud-opt-server-claim
      - name: nextcloud-ssl
        secret:
          secretName: nextcloud-net-tls  
