apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - image: ghcr.io/linuxserver/nextcloud
          name: nextcloud
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1041"
            - name: TZ
              value: America/Los_Angeles
            # TODO: Redis statefulset
            #- name: REDIS_HOST
            #  value: redis
            - name: MYSQL_HOST
              value: mariadb 
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: nextcloud-db-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: nextcloud-db-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: nextcloud-db-secret
            - name: NEXTCLOUD_ADMIN
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN
                  name: nextcloud-db-secret 
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_PASSWORD
                  name: nextcloud-db-secret 
            - name: NEXTCLOUD_TRUSTED_DOMAINS 
              value: homeserver.interal 
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: nextcloud
              subPath: config
            - mountPath: /data
              name: nextcloud
              subPath: data
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-opt-server-claim
