---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-opt-server-volume
  namespace: nextcloud
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/nextcloud/server"
