---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-opt-claim
  namespace: nextcloud
spec:
  storageClassName: nfs
  volumeName: nextcloud-opt-volume
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
