---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-service
  namespace: nextcloud
  labels:
    app: nextcloud-db-service
spec:
  type: ClusterIP
  selector:
    app: nextcloud-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
