---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app: nextcloud-db
spec:
  serviceName: nextcloud-db-service
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        app: nextcloud-db
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
        - name: nextcloud-mariadb
          image: linuxserver/mariadb:latest
          ports:
            - containerPort: 3306
          #args:
          #  - --transaction-isolation=READ-COMMITTED
          #  - --binlog-format=ROW
          #  - --max-connections=1000
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          envFrom:
            - secretRef:
                name: nextcloud-db-secret
          securityContext:
            privileged: true
          volumeMounts:
            - name: nextcloud-db-storage
              mountPath: /config
              subPath: mariadb-config
      volumes:
        - name: nextcloud-db-storage
          persistentVolumeClaim:
            claimName: nextcloud-opt-claim
