apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: | 
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/kawadeomkar
  services.yaml: |
    - Home:
        - Home Assistant:
            icon: home-assistant
            href: http://hass.homeserver.internal/
            ping: http://hass.homeserver.internal/

    - Monitoring:
        - Prometheus:
            icon: prometheus
            href: http://prometheus.homeserver.internal/
            ping: http://prometheus.homeserver.internal/
            widget:
                type: prometheus
                url: http://prometheus.homeserver.internal/

    - Media:
        - Temporary:
            icon: jellyfin
            href: http://localhost/
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
