apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: | 
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/kawadeomkar
  services.yaml: |
    - Home:
        - Home Assistant:
            icon: home-assistant
            href: http://hass.homeserver.internal/
            ping: http://10.0.0.4:30002

    - Monitoring:
        - Prometheus:
            icon: prometheus
            href: http://prometheus.homeserver.internal/
            ping: http://10.0.0.4:30001

        - Grafana:
            icon: grafana
            href: http://grafana.homeserver.internal/
            ping: http://10.0.0.4:30005

    - Media:
        - Jellyfin:
            icon: jellyfin
            href: http://jellyfin.homeserver.internal/
            ping: http://10.0.0.4:30006

        - Sonarr:
            icon: sonarr
            href: http://sonarr.homeserver.internal/
            ping: http://10.0.0.4:30004

        - Radarr:
            icon: radarr
            href: http://radarr.homeserver.internal/
            ping: http://10.0.0.4:30010

        - Prowlarr:
            icon: prowlarr
            href: http://prowlarr.homeserver.internal/
            ping: http://10.0.0.4:30011
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
