---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  namespace: frigate
  labels:
    app: frigate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      containers:
        - env:
            - name: FRIGATE_RTSP_PASSWORD
              value: password
          image: ghcr.io/blakeblackshear/frigate:stable
          name: frigate
          ports:
            - containerPort: 5000
            - containerPort: 8554
            - containerPort: 8555
            - containerPort: 8555
              protocol: UDP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /config/config.yml
              name: frigate-config
            - mountPath: /media/frigate
              name: frigate-media
            - mountPath: /tmp/cache
              name: frigate-tmpcache
            - mountPath: /dev/shm
              name: frigate-dshm
            - mountPath: /dev/dri
              name: frigate-drivers
            - mountPath: /db
              name: frigate-db
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/localtime
          name: localtime
        - hostPath:
            path: /opt/frigate/config.yml
          name: frigate-config
        - hostPath:
            path: /opt/frigate/storage
          name: frigate-media
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: frigate-tmpcache
        - emptyDir:
            medium: Memory
            sizeLimit: 1Gi
          name: frigate-dshm
        - hostPath:
            path: /dev/dri
          name: frigate-drivers
        - hostPath:
            path: /opt/frigate-db
          name: frigate-db
