apiVersion: v1
kind: Service
metadata:
  name: node-exporter-lb
  namespace: ingress
  # namespace: node-exporter
  annotations:
    metallb.universe.tf/allow-shared-ip: "node-exporter-shared-ip"
spec:
  selector:
    # app: node-exporter
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.7
  ports:
    - name: node-exporter
      protocol: TCP
      port: 7878
      targetPort: 7878
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-exporter-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: node-exporter.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node-exporter
                port:
                  number: 7878
