---
- name: install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
# - name: Copy fail2ban custom configuration file into place.
#   template:
#     src: "{{ security_fail2ban_jail_local }}"
#     dest: /etc/fail2ban/jail.local
#     owner: root
#     group: root
#     mode: 0644
#
# - name: update configuration file - /etc/fail2ban/fail2ban.local
#   template:
#     src: "{{ security_fail2ban_local }}"
#     dest: /etc/fail2ban/fail2ban.local
#     owner: root
#     group: root
#     mode: 0644
- name: start and enable fail2ban
  # TODO: copy over j2 of fail2ban/jail.local from /templates
  # and set vars in /defaults

  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
