---
- name: Create container services directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/media/data
    - /opt/sabnzbd/config
    - /opt/jellyfin/config
    - /opt/sonarr/config
    - /opt/radarr/config
    - /opt/prowlarr/config
    - /opt/jellyseerr/config
    - /opt/nextcloud/db
    - /opt/nextcloud/server
    - /opt/homarr/configs
    - /opt/homarr/icons
    - /opt/dashy/item-icons
    - /opt/grafana/storage
    - /opt/filebrowser

- name: Ensure container service files exist
  ansible.builtin.copy:
    content: ""
    dest: "{{ item }}"
    force: false
    group: sys
    owner: root
    mode: 0555
  loop:
    - /opt/dashy/config.yml
