---

- name: Create container services directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - /opt/hass
    - /opt/portainer
    - /opt/jellyfin/config
    - /opt/jellyfin/data