---
- name: Create container services directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: "0755"
    recurse: true
  loop: "{{ service_dirs | map('regex_replace', '^', services_base_dir + '/') | list }}"

# TODO: Add all config files
# - name: Ensure container service files exist
#   ansible.builtin.copy:
#     content: ""
#     dest: "{{ item }}"
#     force: false
#     group: sys
#     owner: root
#     mode: 0555
#   loop:
#     - "{{ services_base_dir }}/dashy/config.yml"
