---

- include_tasks: "setup.yml"
- include_tasks: "ssh.yml"
- include_tasks: "env.yml"

# Debian based tasks
# TODO: depends on k8s ingress config
# - include_tasks: "ubuntu-ufw.yml"
#   when: ansible_os_family == "Debian"

- include_tasks: "fail2ban.yml"
  when: ansible_os_family == "Debian"
