---
- name: Setup environment
  ansible.builtin.include_tasks: "setup.yml"

- name: Setup SSH configuration
  ansible.builtin.include_tasks: "ssh.yml"

- name: Pull secrets from environment variables
  ansible.builtin.include_tasks: "env.yml"

- name: Setup NFS share from NAS
  ansible.builtin.include_tasks: "nfs.yml"

# TODO: depends on k8s ingress config
# - include_tasks: "ubuntu-ufw.yml"
#   when: ansible_os_family == "Debian"

- name: Install fail2ban
  ansible.builtin.include_tasks: "fail2ban.yml"
  when: ansible_os_family == "Debian"

- name: Setup filesystem directories
  ansible.builtin.include_tasks: "filesystem.yml"

# TODO: Needs DNS configuration on router
#- name: Setup pihole 
#  ansible.builtin.include_tasks: "setup-pihole.yml"

- name: Setup tailscale
  ansible.builtin.include_tasks: "tailscale.yml"
  when: tailscale_auth_key is defined
