---
- name: Create local directory for nfs mount "{{ nfs_path }}"
  ansible.builtin.file:
    path: "{{ nfs_path }}"
    state: directory
    recurse: true
    #owner: "{{ username }}"
    #group: "{{ username }}"
    #mode: "0644"

- name: Add New server to /etc/exports
  lineinfile:
    path: /etc/exports
    create: true
    insertafter: EOF
    line: "{{ nfs_path }} {{ nfs_ip }}(rw,sync,no_root_squash)"

- name: Mount share from nfs
  ansible.posix.mount:
    src: "{{ nfs_ip }}:{{ nfs_src_path }}"
    path: "{{ nfs_path }}"
    opts: rw,vers=4.1
    fstype: nfs
    state: mounted

- name: Create package directory for nfs mount "{{ nfs_path }}"
  ansible.builtin.file:
    path: "{{ nfs_path }}{{ item }}"
    state: directory
    recurse: true
    owner: "{{ nfs_owner_uid }}"
    group: "{{ nfs_owner_gid }}"
    mode: "0755"
  loop: "{{ service_dirs | map('regex_replace', '^', '/') | list }}"
