---

- name: create groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - "{{ username }}"
    - docker

- name: create non-root user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
    append: true
    shell: "{{ shell }}"
    # only on initial user create
    update_password: on_create

- name: passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Update apt cache & upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: "3600"

- name: Install core packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Clone homeserver repository
  ansible.builtin.git:
    repo: https://github.com/kawadeomkar/homeserver.git
    # TODO: Move version to vars file
    version: "09f728483479193d3b8c86b8dce6ac427144b541"
    dest: /homeserver
    clone: true
    update: true
