---
- name: create groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - "{{ username }}"
    - docker

- name: create non-root user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker
      - users
    append: true
    shell: "{{ shell }}"
    # only on initial user create
    update_password: on_create

- name: passwordless sudo for "{{ username }}"
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Update apt cache & upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
    cache_valid_time: "3600"

- name: Install core apt packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Ignore PEP 668 - temporary for ubuntu 24
  ansible.builtin.file:
    path: /usr/lib/python3.12/EXTERNALLY-MANAGED
    state: absent

- name: Install pip `community.kubernetes` pre-requisites
  ansible.builtin.pip:
    name:
      - openshift
      - pyyaml
      - kubernetes

