---

- name: Ensure curl is present
  ansible.builtin.apt: name=curl state=present

- name: Disable tailscale if running
  command: "tailscale down"

- name: Add tailscale GPG key
  ansible.builtin.shell: "curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null"
  changed_when: false

- name: Add tailscale GPG key
  ansible.builtin.shell: "curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null"
  changed_when: false

- name: Add tailscale package repository
  ansible.builtin.shell: >
    curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
  changed_when: false

- name: Run apt-get update to update with tailscale pkg repo list
  ansible.builtin.apt: update_cache=true

- name: Install Tailscale package
  ansible.builtin.apt:
    name: tailscale
    state: present

# Setup subnet routing

- name: Ensure net.ipv4.ip_forward is set to 1 in /etc/sysctl.d/99-tailscale.conf
  lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: 'net.ipv4.ip_forward = 1'
    state: present
    create: yes 
  
- name: Ensure net.ipv6.conf.all.forwarding is set to 1 in /etc/sysctl.d/99-tailscale.conf
  lineinfile:
    path: /etc/sysctl.d/99-tailscale.conf
    line: 'net.ipv6.conf.all.forwarding = 1'
    state: present
    create: yes

- name: Apply sysctl settings from /etc/sysctl.d/99-tailscale.conf
  command: sysctl -p /etc/sysctl.d/99-tailscale.conf

- name: Connect, authenticate machine to tailnet and advertise routes with tailscale
  ansible.builtin.command: "tailscale up --authkey {{ tailscale_auth_key }} --stateful-filtering"
