---
# TODO: Move state version to vars file
- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    update_cache: true
    state: present
# TODO: Allow certain ports
# - name: UFW deny incoming
#   ufw:
#     direction: incoming
#     proto: any
#     policy: deny
#   notify:
#   - reload ufw
- name: UFW allow outgoing
  community.general.ufw:
    direction: outgoing
    proto: any
    policy: allow
  notify:
    - reload ufw
# TODO:
# - name: UFW configure ports
#   ufw:
#     rule: "{{ item.rule }}"
#     interface: "{{ item.interface | default('') }}"
#     direction: "{{ item.direction | default('in') }}"
#     from_ip: "{{ item.from_ip | default('any') }}"
#     to_ip: "{{ item.to_ip | default('any') }}"
#     from_port: "{{ item.from_port | default('') }}"
#     to_port: "{{ item.to_port | default('') }}"
#     protocol: "{{ item.protocol | default('any') }}"
#     route: "{{ item.route | default(omit) }}"
#     log: "{{ item.log | default(false) }}"
#     comment: "{{ item.comment | default(omit) }}"
#   with_items: "{{ ufw_rules }}"
#   notify: reload ufw
- name: UFW allow ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH
  notify:
    - reload ufw
- name: Enable UFW
  community.general.ufw:
    state: enabled
