---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
  labels:
    app: grafana
data:
  plugins: grafana-piechart-panel
  grafana.ini: |
    [auth.anonymous]
      enabled = true
      org_role = Viewer
      hide_version = false
    [analytics]
      reporting_enabled = false
      check_for_updates = false
    [log]
      mode = console
      level = info
    [paths]
      data         = /var/lib/grafana/data
      logs         = /var/log/grafana
      plugins      = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
    [security]
      allow_embedding = true