---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-opt-volume
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/grafana"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-opt-claim
  namespace: monitoring
spec:
  volumeName: grafana-opt-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
