apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: jellyseerr
  labels:
    app: jellyseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr
          imagePullPolicy: Always
          ports:
            - containerPort: 5055
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - mountPath: /app/config
              name: jellyseerr
      volumes:
        - name: jellyseerr
          hostPath:
            path: /opt/jellyseerr/config
