apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-lb
  namespace: ingress
  # namespace: jellyseerr
  annotations:
    metallb.universe.tf/allow-shared-ip: "jellyseerr-shared-ip"
spec:
  selector:
    # app: jellyseerr
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.10
  ports:
    - name: jellyseerr
      protocol: TCP
      port: 5055 
      targetPort: 5055
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr-ingress
  namespace: jellyseerr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: jellyseerr.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 5055
