---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-opt-volume
  namespace: homeassistant
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: "/opt/hass"
  nfs:
    path: /mnt/nvme/store/hass
    server: truenas.local
    readOnly: false


# TODO: Add DNS hostnames 
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - DNS.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-opt-claim
  namespace: homeassistant
  labels:
    io.kompose.service: homeassistant-opt-claim
spec:
  volumeName: homeassistant-opt-volume
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
