apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  type: NodePort
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: homeassistant
status:
  loadBalancer: {}
