apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homeassistant
  creationTimestamp: null
  labels:
    io.kompose.service: homeassistant-claim1
  name: homeassistant-claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
