apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-opt-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/hass"

# TODO: Add DNS hostnames 
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#      - matchExpressions:
#        - key: kubernetes.io/hostname
#          operator: In
#          values:
#          - DNS.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-opt-claim
  labels:
    io.kompose.service: homeassistant-opt-claim
spec:
  volumeName: homeassistant-opt-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
