apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-opt-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/hass"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-opt-claim
  labels:
    io.kompose.service: homeassistant-opt-claim
spec:
  volumeName: homeassistant-opt-volume
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
