apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  # Using NodePort to access with IP Address
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8123
      nodePort: 30002
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8123
      nodePort: 30003
  selector:
    app: homeassistant
