apiVersion: v1
kind: Service
metadata:
  name: homarr-lb
  namespace: ingress
  # namespace: homarr
  annotations:
    metallb.universe.tf/allow-shared-ip: "homarr-shared-ip"
spec:
  selector:
    # app: homarr
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.1.4
  ports:
    - name: homarr
      protocol: TCP
      port: 7575
      targetPort: 7575
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr-ingress
  namespace: homarr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: homarr.homeserver.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homarr
                port:
                  number: 7575
