---

- name: create groups
  group: 
    name: "{{ item }}"
  loop:
    - "{{ username }}"
    - docker


- name: create non-root user
  user: 
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
      - docker 
      - users
    append: yes
    shell: "{{ shell }}"
    # only on initial user create
    update_password: on_create

- name: passwordless sudo for "{{ username }}"
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Install core packages
  apt:
    name: "{{ packages }}"
    state: latest


# TODO: Revisit to pin versions to avoid breaking changes.
#- name: Update packages to the latest version. 
#  apt:
#    update_cache: yes
#    upgrade: yes